### ISSUE TITLE
Clearer sleep mode instructions?

### ISSUE THREAD

**Issue by klundry** [dezign999/watchy999#2]
How exactly does sleep mode work? The time that you set is when it enters sleep mode? When does it come out of sleep mode?

**Comment by klundry** [comment]
Ah, ok. After playing around with it I see that just pressing a button wakes it back up.

PS. This project is great. Excellent work and thanks for sharing. I'm loving it. :-)

**Comment by dezign999** [comment]
Docs aren't complete, but I see you've figured it out.
